name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Triggers on tags that start with 'v'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install build tools
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Build the package
      - name: Build package
        run: python -m build

      # Publish to PyPI
      - name: Publish package
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
